---
- name: Determine if Atomic
  command: "grep Atomic /etc/redhat-release"
  register: is_atomic
  ignore_errors: yes
  changed_when: false

- name: Determine if RHEL7
#  shell: "grep 'Red Hat Enterprise Linux.*release 7' /etc/redhat-release"
  shell: "echo 'ok'"
  register: is_rhel7
  ignore_errors: yes
  changed_when: false

- include: rhel7_repos.yml
  when: is_rhel7.rc == 0 and is_atomic.rc != 0

- name: Determine if firewalld installed
  command: "rpm -q firewalld"
  register: has_firewalld
  ignore_errors: yes
  changed_when: false

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: has_iptables
  ignore_errors: yes
  changed_when: false
